# Site settings
title: Breno Oliveira
email: breno26 [at] gmail [dot] com
description: ""
baseurl: ""
url: "http://brenooliveira.com.br"
# url: "http://localhost:3000"
twitter_username: brenoholiveira
github_username:  brenooliveira
linkedin_username: br.linkedin.com/pub/breno-oliveira/a/713/54a/
rubygem_username: brenoholiveira
slideshare_username: brenoholiveira
gtalk_username: breno26@gmail.com
skype_username: brenohdo

port: 3000

# Build settings
markdown: kramdown
permalink: pretty

highlighter: true
